---
- name: "Установка редис воркеров очереди Yii2"
  template:
    src: yii-queue@.service.j2
    dest: /etc/systemd/system/yii-queue@.service
    owner: root
    group: root
    mode: 0644
  with_items:
    - DOMAIN_NAME: "{{ DOMAIN_NAME }}"
      web_root: "{{ web_root }}"

- name: Перечитать конфиги systemd (>=2.4)
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Запуск и автозагрузка юнитов yii-queue@* (Должны быть добавлены в автозагрузку как через - systemctl enable yii-queue@1 yii-queue@2)
  ansible.builtin.systemd_service:
    state: started
    enabled: true
    name: "{{ item }}"
  with_items:
    - "yii-queue@1"
    - "yii-queue@2"
