##########################################################
# `snake_case` для Ansible-переменных не просто конвенция, а практическое требование Jinja2 — `php-version` он трактует
# как `php` минус `version`.
##########################################################

##########################################################
# GLOBAL
##########################################################

domain_name: domain.zone
host_ip: "{{ hostvars[groups['site'][0]]['ansible_host'] }}" # А это где-то нужно?
web_root: "/var/www"
locale1: ru_RU.UTF-8
locale2: en_US.UTF-8
time_zone: UTC # Asia/Yekaterinburg # Europe/Moscow
