##########################################################
# GLOBAL
##########################################################

domain_name: domain.zone
host_ip: "{{ hostvars[groups['site'][0]]['ansible_host'] }}" # А это где-то нужно?
web_root: "/var/www"
locale1: ru_RU.UTF-8
locale2: en_US.UTF-8
time_zone: UTC # Asia/Yekaterinburg # Europe/Moscow
