---
# NOTE: Если не закомментировать после шифрования, то пароли отсюда подтягиваются вместо "secrets.vault"
# Пароль root а удалённом сервере до того как перешли на использование SSH ключей.
#vault_ansible_password: "0000000000000000"
# Парольная фраза для SSH ключа
#vault_ssh_key_passphrase: "Uvn8^Ua0+CmV``LxZ$_tK^R!z&Af6U9KC(t"
# Пароль к базе данных
#vault_mysql_db_user_password: "5/>h_$X/Fgg}(wa#_jdh_[dfjyE"#3E7p{Q"
# Пароль root к базе данных
#vault_mysql_root_password:  "5/>Oh_$X/Fgg}(wa#_jdh5_[dfj4yE2#3E7p{Q2"
