---
##########################################################
# FAIL2BAN
##########################################################

# fail2ban_version: 1.1.0 # v=1.0.2-3 Предустановлена в Ubuntu 24.04.3 (Noble Numbat). При попытке установить любую версию показывает ошибку что дистрибутив не найден в репозитории
ban_time: 3600 # default - 10m
find_time: 600 # default - 10m
max_retry: 5
# NB: Защищаем точки входа, а не всё подряд.
# Если сервис имеет доступ снаружи сервера, тогда защищаем,
# иначе просто закрываем доступ извне на уровне фаервола.
jails_enable_status:
  # Предустановленные
  sshd: true
  nginx_http_auth: true
  nginx_limit_req: false # Чтобы включить, сначала прочитай описание в файле конфига
  nginx_botsearch: true
  nginx_bad_request: true
  nginx_forbidden: true
  php_url_fopen: true
  vsftpd: false # Не устанавливаем. Зачем, если есть WinSCP
  mysqld_auth: false # Слушает только localhost
  traefik_auth: false # Сначала настрой его. :)
  recidive: true
  sendmail_auth: false
  sendmail_reject: false
  # Добавленные
  redis_auth: false # Слушает только localhost
  # Ниже два правила одного и того же. php_fpm - устаревшее, оставлено на всякий случай,
  # удаляем после полной настройки или описания процесса настройки для yii2_auth
  php_fpm: false # Для защиты от брутфорса PHP-приложений. Логирование см. ANALYSIS 3.2.6
  yii2_auth: false # Включится после внедрения Monolog→SyslogHandler в Yii2. См. ANALYSIS 3.2.6





