---
##########################################################
# SSH-USERS
##########################################################

############### Общее
LOCAL_HOME_PATH: "{{ lookup('env', 'HOME') }}"
force_key_regen: false # true — принудительно регенерировать ключи (бэкапит существующие в той же директории)
ssh_known_hosts_path: "{{ LOCAL_HOME_PATH }}/.ssh/known_hosts"
ssh_key_type: "ed25519" # или "rsa" (только если не поддерживается ed25519, например, если версия OpenSSH ниже 6.5)
ssh_key_size: 0 # Для RSA указать `4096`. Для ed25519 длина фиксированная.
ssh_key_passphrase: "{{ vault_ssh_key_passphrase }}"
target_ssh_port: 22 # TODO - лучше потом поменять порт по умолчанию для SSH

############### Пути к ключам
local_ssh_keys_dir: "{{ LOCAL_HOME_PATH }}/.ssh"
# ssh_keys_dir: "{{ ansible_env.HOME }}/.ssh" # ansible_env — это facts целевого хоста, а не контроллера
ordinary_key_path: "{{ local_ssh_keys_dir }}/key_{{ DOMAIN_NAME }}"
ordinary_pubkey_path: "{{ ordinary_key_path }}.pub"
emergency_key_path: "{{ local_ssh_keys_dir }}/key_{{ DOMAIN_NAME }}_emergency_root"
emergency_pubkey_path: "{{ emergency_key_path }}.pub"

############### Куда копируем
target_host: "{{ hostvars[groups['site'][0]]['ansible_host'] }}"

############### Подключение Ansible
site_ansible_user: root
site_ansible_password: "{{ vault_root_password }}" # Сначала пароль, потом копирование ключей, потом уже без пароля. Чтобы автоматизировать копирование ключей, нужен пароль.
site_ansible_key: ~

############### Новый sudo пользователь вместо root
new_user: "bes" # Укажите имя нового пользователя
