; Отключаем опасные функции
disable_functions = system,exec,shell_exec,passthru,proc_open,popen,proc_close,curl_multi_exec,parse_ini_file,show_source,phpinfo

; Не раскрывать версию PHP в HTTP-заголовках
expose_php = Off

; Отключаем удалённые URL в file-функциях (RFI-вектор)
allow_url_fopen = Off
allow_url_include = Off
