; Максимальный размер одного файла
upload_max_filesize = 500M
; Максимальный размер POST-запроса (с запасом под текстовые поля и заголовки)
post_max_size = 550M
; Лимит памяти для скрипта (с запасом, чтобы PHP мог обработать запрос и выполнить код)
memory_limit = 700M
