---
#Configure AppArmor for Nginx, PHP-FPM, MySQL, and Redis
- name: Install AppArmor packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apparmor
    - apparmor-utils
    - apparmor-profiles

# Профиль для Nginx
- name: Create AppArmor profile for Nginx
  template:
    src: usr.sbin.nginx.j2
    dest: /etc/apparmor.d/usr.sbin.nginx
    mode: '0644'
  notify: Reload AppArmor

- name: Set Nginx profile to complain mode
  command: aa-complain /etc/apparmor.d/usr.sbin.nginx
  changed_when: false
  notify: Reload AppArmor

# Профиль для PHP-FPM (основной процесс)
- name: Create AppArmor profile for PHP-FPM
  template:
    src: usr.sbin.php-fpm.j2
    dest: /etc/apparmor.d/usr.sbin.php-fpm{{ php-version }}
    mode: '0644'
  notify: Reload AppArmor

- name: Set php-fpm profile to complain mode
  command: aa-complain /etc/apparmor.d/usr.sbin.php-fpm{{ php-version }}
  changed_when: false
  notify: Reload AppArmor

# Профиль для MySQL
- name: Create AppArmor profile for MySQL
  template:
    src: usr.sbin.mysqld.j2
    dest: /etc/apparmor.d/usr.sbin.mysqld
    mode: '0644'
  notify: Reload AppArmor

- name: Set mysqld profile to complain mode
  command: aa-complain /etc/apparmor.d/usr.sbin.mysqld
  changed_when: false
  notify: Reload AppArmor

# Профиль для Redis
- name: Create AppArmor profile for Redis
  template:
    src: usr.bin.redis-server.j2
    dest: /etc/apparmor.d/usr.bin.redis-server
    mode: '0644'
  notify: Reload AppArmor

- name: Set redis-server profile to complain mode
  command: aa-complain /etc/apparmor.d/usr.bin.redis-server
  changed_when: false
  notify: Reload AppArmor

# Профиль для fail2ban
- name: Create AppArmor profile for fail2ban
  template:
    src: usr.sbin.fail2ban-server.j2
    dest: /etc/apparmor.d/usr.sbin.fail2ban-server
    mode: '0644'
  notify: Reload AppArmor

- name: Set fail2ban-server profile to complain mode
  command: aa-complain /etc/apparmor.d/usr.sbin.fail2ban-server
  changed_when: false
  notify: Reload AppArmor
