---
- name: Ensure Redis is present
  become: true
  apt:
   name: redis-server
   state: present
   update_cache: yes
  register: apt_result
  until: apt_result is success
  retries: 5       # Попробовать 5 раз
  delay: 10        # Ждать 10 секунд между попытками
  notify: Start redis on boot

- name: Ensure Redis data directory exists
  become: true
  ansible.builtin.file:
    path: /var/lib/redis
    state: directory
    owner: redis
    group: redis
    mode: 0755

- name: Create a directory "/etc/redis", if it does not exist
  become: true
  ansible.builtin.file:
    path: /etc/redis
    state: directory
    mode: 0755

- name: Ensure Redis Configuration
  become: true
  template:
    src: redis.conf.j2
    dest: /etc/redis/redis.conf
    owner: root
    group: root
    mode: 0644
  notify: Restart redis

- name: Create redis systemd override directory
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/redis-server.service.d
    state: directory
    mode: 0755
  notify: Restart redis

- name: Configure redis to log to journald
  become: true
  ansible.builtin.copy:
    dest: /etc/systemd/system/redis-server.service.d/override.conf
    content: |
      [Service]
      StandardOutput=journal
      StandardError=journal
      SyslogIdentifier=redis
    mode: 0644
  notify: Restart redis
