---
-   name: Install certbot + nginx plugin
    apt:
      name:
        - certbot
        - python3-certbot-nginx
      state: present
      update_cache: yes

-   name: Build list of -d arguments from nginx_sites
    set_fact:
      certbot_domains_args: >-
        {{ nginx_sites | map(attribute='server_name')
                       | map('split', ' ')
                       | flatten
                       | map('regex_replace', '^(.+)$', '-d \1')
                       | join(' ') }}

-   name: Request Let's Encrypt certificates
    command: >
      certbot --nginx --non-interactive --agree-tos
              -m {{ certbot_email }}
              {{ certbot_domains_args }}
    args:
      creates: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"

-   name: Ensure certbot renew timer is enabled
    systemd:
      name: certbot.timer
      enabled: yes
      state: started
