---
- name: Install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  register: apt_result
  until: apt_result is success
  retries: 5       # Попробовать 5 раз
  delay: 10        # Ждать 10 секунд между попытками
  notify: Start MySQL on boot

- name: Создание файла логов медленных запросов
  file:
    path: /var/log/mysql/slow-queries.log
    owner: mysql
    group: mysql
    mode: 0640
    state: touch
  notify: Restart mysql
