---
- name: Backup SSH configuration
  ansible.builtin.copy:
    src: /etc/ssh/sshd_config
    dest: /etc/ssh/sshd_config.bak
    remote_src: yes
    mode: '0600'

# Маленький нюанс для цикла ниже: Если в вашем sshd_config есть блоки Match (например, Match User backup),
# lineinfile может добавить новые строки в конец файла, то есть внутрь этого блока, что изменит их логику.
# Если блоков Match нет — схема с циклом ниже рабочая.
- name: Hardening SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#?{{ item.key }}"
    line: "{{ item.key }} {{ item.value }}"
    state: present
    validate: '/usr/sbin/sshd -t -f %s'
  loop:
    # Аутентификация
    - { key: 'PasswordAuthentication', value: 'no' } # Запрещает вход по паролю для всех пользователей. Вход только по ключам.
    - { key: 'KbdInteractiveAuthentication', value: 'no' } # Для 2FA (Google Authenticator) или расширенного PAM. Если вы поставите `PasswordAuthentication no`, но оставите `KbdInteractiveAuthentication yes`, вы все равно сможете войти по обычному паролю, так как PAM запросит его через этот «интерактивный» интерфейс.
    - { key: 'ChallengeResponseAuthentication', value: 'no' } # Это устаревшее название для `KbdInteractiveAuthentication`.
    - { key: 'PubkeyAuthentication', value: 'yes' } # Включает вход по ключам.
    - { key: 'PermitRootLogin', value: 'prohibit-password' } # Запрещает вход под root по SSH с помощью пароля. Оставляет возможность входа только по ключу!.

    # Безопасность и логи
    - { key: 'LogLevel', value: 'VERBOSE' } # LogLevel VERBOSE в OpenSSH записывает подробную информацию о каждом SSH-соединении, включая аутентификацию, используемые криптографические алгоритмы и начало/окончание сессий.
    - { key: 'Protocol', value: '2' } # Устанавливает Protocol 2 (хотя в современных версиях OpenSSH это уже стандарт)

    # Криптография (Ciphers, MACs, Kex)
    - { key: 'Ciphers', value: 'aes256-ctr,chacha20-poly1305@openssh.com' } # Настраивает безопасные алгоритмы шифрования
    - { key: 'MACs', value: 'hmac-sha2-512,hmac-sha2-256' } # Настраивает безопасные MAC-алгоритмы
    - { key: 'KexAlgorithms', value: 'curve25519-sha256,curve25519-sha256@libssh.org' } # Настраивает безопасные алгоритмы обмена ключами
    - { key: 'HostKeyAlgorithms', value: 'ssh-ed25519,rsa-sha2-512,rsa-sha2-256' } # Настраивает безопасные алгоритмы хостовых ключей

    # Тайм-ауты (Подробное описание ниже)
    - { key: 'ClientAliveInterval', value: '300' } # Период пинга
    - { key: 'ClientAliveCountMax', value: '3' } # Количество попыток пинга
  notify: Restart SSH

########################################################################
# Тайм-аут разрыва соединения: 300 сек × 3 = 15 минут тайм-аут.
# ClientAliveInterval (300 сек.) × ClientAliveCountMax (3 сек.) = 900 сек (15 мин.)
# Сервер каждые `ClientAliveInterval` отправляет "пинг" подключённому клиенту, чтобы проверить, что соединение живое.
# Если клиент не отвечает (сеть упала, клиент завис), соединение автоматически разрывается.
# Для очистки "зависших" сессий: Если клиент "завис" (браузер крашнулся, сеть упала), сессия не висит "вечно".
# ClientAliveInterval - период пинга
# ClientAliveCountMax - количество попыток пинга
########################################################################

- name: Validate SSH configuration # Выдаст ошибку, если конфиг некорректен
  ansible.builtin.command: sshd -t
  changed_when: false
  failed_when: sshd_test.rc != 0
  register: sshd_test
  notify: Restart SSH






