---
- name: Sync site files # https://stackoverflow.com/a/27995384 (обертка над `rsync`)
  ansible.posix.synchronize:
    src: "FULL_ABSOLUTE_PATH??"
    dest: {{ web_root }}/{{ domain_name }}/
    delete: yes # Удалит файлы на сервере, которых нет локально (опционально)
    # checksum=true # По-умолчанию rsync использует для сравнения "mod-time" и "file size", если нужно сравнивать по содержимому, то включить эту опцию (checksum=true)

- name: Change file ownership, group and permissions (7777)
  ansible.builtin.file:
    path: [
      "{{ web_root }}/{{ domain_name }}/pub/storage/runtime",
      "{{ web_root }}/{{ domain_name }}/pub/web/static/cache",
      "{{ web_root }}/{{ domain_name }}/pub/web/static/files",
      "{{ web_root }}/{{ domain_name }}/pub/web/static/origin",
      "{{ web_root }}/{{ domain_name }}/pub/web/front/assets",
      "{{ web_root }}/{{ domain_name }}/pub/web/back/assets",
    ]
    owner: "www-data"
    group: "www-data"
    mode: '7777' # TODO Должно быть максимум `0755` (или `0775` с  правильной группой).
    recurse: yes

- name: Copy db dump on server
  copy:
    src: ../../mysql_dump/dump.sql
    dest: "{{ web_root }}/dump.sql"

- name: MySQL dump
  mysql_db:
    name: domain_name_db
    state: import
    target: "{{ web_root }}/dump.sql"
    login_user: root
#    login_password: "{{ mysql_root_password }}"

- name: Remove remote dump.sql
  ansible.builtin.file:
    path: "{{ web_root }}/dump.sql"
    state: absent
