##########################################################
#
# Playbook для локальных задач
# 1) Создание SSH-ключей (обычный и аварийный) на локальном хосте
# 2) Обновление `~/.ssh/known_hosts` с добавлением ECDSA-записи удалённого хоста
#
##########################################################
---
- name: Generate SSH keys
  hosts: localhost
  vars_files:
    - ../secrets/secrets.vault
    - ../group_vars/global.yml
  roles:
    - ../roles/system/ssh_generate_local_keys
    - ../roles/system/ssh_add_remote_host_to_known_hosts
