##########################################################
#
# Playbook для тестирования изменений
# внесённых при работе на удалённом хосте
#
##########################################################
---
- name: Testing server
  hosts: site
  roles:
    - ../roles/3-tests
