##########################################################
#
# Playbook для тестирования изменений
# внесённых при работе на удалённом хосте
#
##########################################################
---
- name: Testing server
  hosts: site
  vars_files:
    - ../secrets/secrets.vault
    - ../group_vars/global.yml
  roles:
    - ../roles/3-tests
