##########################################################
#
# Проверка доступа по ключам
# 1) Для нового sudo пользователя
# 2) Для root
#
##########################################################
---
- name: Basic server configuration
  hosts: site
  roles:
    - ../roles/tests
